In [1]:
import pandas
from numpy import corrcoef
from sklearn.decomposition import PCA

In [2]:
prices = pandas.read_csv('close_prices.csv')
prices.pop('date')
prices.head()

AXP          BA        CAT       CSCO         CVX         DD  \
0  76.440002  117.510002  85.029999  24.270000  125.519997  59.409999   
1  76.070000  119.000000  85.110001  24.139999  124.489998  59.319997   
2  75.989998  118.510002  84.500000  24.430000  124.070000  59.319997   
3  76.320000  119.379997  84.199997  23.770000  123.489998  59.509996   
4  75.889999  118.739998  83.800003  23.330000  122.639999  59.009995   

         DIS         GE          GS         HD    ...            PFE  \
0  64.750000  24.280001  165.250000  75.910004    ...      28.799999   
1  64.320000  24.320000  162.970001  76.040001    ...      28.709999   
2  64.449997  24.230000  162.309998  75.519997    ...      28.490000   
3  65.239998  24.250000  162.289993  76.070000    ...      28.520000   
4  65.190002  24.049999  159.850006  75.959999    ...      28.879999   

          PG          T        TRV        UNH         UTX           V  \
0  79.279999  34.220001  86.379997  71.820000  109.419998  196.240005   
1  78.620003  34.090000  85.870003  72.320000  110.000000  193.339996   
2  77.720001  34.049999  85.980003  71.980003  109.260002  191.559998   
3  78.050003  34.230000  85.830002  72.160004  109.660004  193.559998   
4  77.209999  33.980000  85.410004  71.989998  109.360001  193.050003   

          VZ        WMT        XOM  
0  47.980000  76.419998  87.750000  
1  47.270000  75.750000  87.360001  
2  46.950001  74.650002  87.139999  
3  47.669998  74.620003  87.070000  
4  47.000000  74.360001  86.900002  

[5 rows x 30 columns]

In [3]:
pca = PCA(n_components = 10)
pca = pca.fit(prices)
pca.explained_variance_ratio_

array([ 0.73897118,  0.11007169,  0.04995088,  0.0287492 ,  0.02215448,
        0.01931577,  0.00674853,  0.00614091,  0.00320594,  0.00305611])

In [4]:
test = pandas.read_csv('djia_index.csv')
test.pop('date')
test.head()

^DJI
0  15401.379883
1  15334.589844
2  15273.259766
3  15328.299805
4  15258.240234

In [5]:
pca_prices = pca.transform(prices)
first = pca.components_[0]
for i in range(0, len(first)):
    if first[i] == max(abs(first)):
        print(i)
abs(pca.components_[0])

26


array([  1.61383840e-02,   1.20644923e-01,   5.16612711e-02,
         5.04842369e-02,   1.25859933e-01,   1.14089567e-01,
         2.33906290e-01,   6.20513749e-03,   2.51227032e-01,
         2.88996029e-01,   2.64998795e-01,   9.31320168e-02,
         9.13948403e-02,   4.69879340e-02,   2.90549417e-02,
         2.61068828e-02,   3.29615584e-01,   7.13897133e-02,
         7.62295699e-02,   2.11888868e-01,   2.30922941e-02,
         7.77316954e-02,   7.20594590e-03,   1.89479745e-01,
         3.21564017e-01,   5.36834873e-02,   5.79683946e-01,
         1.09122230e-04,   8.71614334e-02,   4.29421420e-02])

In [6]:
corrcoef(pca_prices[:,0], test['^DJI'])

array([[ 1.        ,  0.90965222],
       [ 0.90965222,  1.        ]])